### ISSUE TITLE
django CMS 3.1 release checklist

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#4048]
* [x] #4047 
 * [x] #4046 
 * [x] divio/djangocms-text-ckeditor#235
 * [x] nephila/djangocms-installer#176
 * [x] nephila/djangocms-helper#33

**Comment by yakky** [comment]
All issue addressed
