### ISSUE TITLE
[META] Dropping 1.6 and code cleanup

### ISSUE THREAD

**Issue by yakky** [divio/django-cms#4580]
Probably not fully pep8/isort compliant at first but let's tackle this

**Dropping django 1.6**:
- [x] #4581

**From #3802**:
- [x] `setup.py`: Python 2.6 classifier and minimum Django version (south also?)
- [x] `from __future__ import with_statement` (for Python 2.6)
- [x] Replace `SortedDict` with `collections.OrderedDict` (need Python 2.7 min.)
- [x] `cms.test_utils.compat` (skipIf unittest2 stuff) (need Python 2.7 min.)
- [x] Usage of `cms.utils.compat.DJANGO_1_6`
- [x] Replace from `django.utils.importlib` with `importlib` (need Python 2.7 min.)

**Other Issues**:
- [x] #3064

**Comment by timgraham** [comment]
I'll be happy to work on this if it's a good time to do so, however, in the past I remember you didn't want to merge similar work until sometime after the previous release so there wouldn't be as many merge conflicts. Let me know if that applies here too.

**Comment by FinalAngel** [comment]
It would be very much appreciated @timgraham. we first need to decide on how to approach the branches. @yakky can we already do a ``support/3.2.x`` and use ``develop`` for 3.3?

In any case @timgraham you could start on a branch yourself and we'll see that it gets merged into the appropriate 3.3 branch once you're ready.

**Comment by yakky** [comment]
@timgraham that would be great!
given that 3.2 has almost no BE change, I think it's not worth to wait for things to settle down and you can start working on it
@FinalAngel yeah, creating the support branch for 3.2 is the best option, how many open PR must go in 3.2.x, I'd wait for them to be merged before branching

**Comment by FinalAngel** [comment]
@yakky we might want to coordinate with @mkoistinen @vxsx and @evildmp let's figure that out later today. I'll let you know asap.

**Comment by yakky** [comment]
Fixed in #4782

**Comment by FinalAngel** [comment]
awesome :)
