### ISSUE TITLE
[META] Menus/pagetree refactor

### ISSUE THREAD

**Issue by FinalAngel** [divio/django-cms#4597]
This issue collects related issues/ideas regarding the pagetree for a refactor in 3.3.

**Pagetree**
- [ ] #3132 UX enhancements
- [ ] #3817 Better Filter Mechanics
- [ ] #3027 How to set "Home" home page
- [ ] #3602 bulk publish all
- [ ] #3718 latin symbols
- [ ] #4000 Import / Export tree via csv or similar
- [ ] #4377 search resets
- [x] #4144 Right click not working properly

**Related**
- [ ] #4303 setting index page

**Comment by FinalAngel** [comment]
Lets close it @Aiky30
